### ISSUE TITLE
AttributeError: 'function' object has no attribute 'command'

### ISSUE THREAD

**Issue by backupandforkacc** [Gransi/awattar#4]
Thanks for your work. I installed with "pip install awattar", but get an error when calling the help function:

```
$ awattar --help
Traceback (most recent call last):
  File "/home/simon/.local/bin/awattar", line 5, in <module>
    from awattar import _cli
  File "/home/simon/.local/lib/python3.10/site-packages/awattar/__init__.py", line 6, in <module>
    from .cli import cli as _cli    # for CLI entry only
  File "/home/simon/.local/lib/python3.10/site-packages/awattar/cli.py", line 34, in <module>
    @cli.command
AttributeError: 'function' object has no attribute 'command'
```

**Comment by Gransi** [comment]
it seems there is a problem with "click" python package. Can you upgrade your python package with `pip install click --upgrade`

**Comment by Gransi** [comment]
new version was released. The issues should be fixed in version.
